version: '3'
services:
  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      # Create a new database. Please note, the
      # /docker-entrypoint-initdb.d/init.js has to be executed
      # in order for the database to be created
      MONGO_INITDB_DATABASE: realestate
    volumes:
      # Add the db-init.js file to the Mongo DB container
      - ./db-init.js:/docker-entrypoint-initdb.d/init.js:ro
    ports:
      - '27017-27019:27017-27019'
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: database
    depends_on:
      - database
  
  web:
    build: .
    image: realestate-angular
    environment:
      # Use the username and password found in the db-init.js file instead
      # of the root username.
      MONGODB_URI: mongodb://user:secretPassword@database/realestate
    depends_on:
      - database
    ports:
      - 8082:5000